---

- name: Notify users
  cron:
    name: timesheet_kitten weekly user notification
    minute: "5"
    hour: "13"
    weekday: "5"
    job: >
      echo '{{ docker_registry_password }}' | docker login -u '{{ docker_registry_username }}' --password-stdin '{{ docker_registry_url }}' ;
      docker run -t --rm '{{ timesheet_kitten_docker_image }}'
      --harvest-api-token '{{ timesheet_kitten_harvest_api_token }}'
      --slack-user-api-token '{{ timesheet_kitten_slack_user_api_token }}'
      --slack-bot-api-token '{{ timesheet_kitten_slack_bot_api_token }}'
      -v
      --notify-all-users
      -s {{ timesheet_kitten_admins | join(' -s ') }}
      >> /var/log/timesheet-kitten.log


- name: Send summary to admins
  cron:
    name: timesheet_kitten admin summary
    minute: "20"
    hour: "13"
    weekday: "5"
    job: >
      echo '{{ docker_registry_password }}' | docker login -u '{{ docker_registry_username }}' --password-stdin '{{ docker_registry_url }}' ;
      docker run -t --rm '{{ timesheet_kitten_docker_image }}'
      --harvest-api-token '{{ timesheet_kitten_harvest_api_token }}'
      --slack-user-api-token '{{ timesheet_kitten_slack_user_api_token }}'
      --slack-bot-api-token '{{ timesheet_kitten_slack_bot_api_token }}'
      -v
      -s {{ timesheet_kitten_admins | join(' -s ') }}
      --skip-summary-comments
      >> /var/log/timesheet-kitten.log


