---

- name: create role docker directory
  file:
    path: /docker/homedepot
    state: directory
    mode: 0755

- name: create postgres directory
  file:
    path: /docker/postgres/data
    state: directory
    mode: 0777

- name: create minio directory
  file:
    path: /docker/minio/data
    state: directory
    mode: 0777

- set_fact:
    restart_docker: no

- name: create docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /docker/homedepot/docker-compose.yml
    mode: 0660
    owner: root
    group: wheel

- name: Log into  registry
  docker_login:
    registry: "{{ docker_registry_url }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
  changed_when: False

- name: run service
  docker_compose:
    project_src: /docker/homedepot/
    pull: yes
    restarted: "{{ restart_docker }}"
  register: run_service_result

- debug:
    var: run_service_result