---

plugin: aws_ec2
regions:
  - eu-west-1

filters:
  tag:ansible_managed: "true"
  instance-state-name: running

hostnames:
  - tag:Name
  - private-ip-address
  - private-dns-name

keyed_groups:
  - prefix: tag
    key: tags

compose:
  ansible_host: private_ip_address
