---

node21_neo4j_version: 3.5.8-enterprise
node21_frontend_version: 19e24c3
node21_backend_version: e4c67ed
node21_env: prod
node21_env_long: production

node21_jwt_secret: -----BEGIN CERTIFICATE-----MIIDATCCAemgAwIBAgIJU1qPC+6W4+AtMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNVBAMTE25vZGUyMS5ldS5hdXRoMC5jb20wHhcNMTkwOTAyMDk1MDA2WhcNMzMwNTExMDk1MDA2WjAeMRwwGgYDVQQDExNub2RlMjEuZXUuYXV0aDAuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+claSEM3AnfKlVAD9aZQ8FiTEt2ROgjfhz/Iivv4Khga6jh5uPBMgiXhmPa2xLiPtq3BKHCBuqBHSW3yyESXHzpmyxFllIWUuU2MmcPNfpwmSiBjWlg82Y9d8VgA7/8H6Up7pQLyZRlsW53jBMxbZClMZN6QhbZ2T1O5EZ5dcXqU1D35bJvpJq5lmvwjIsgdS5TqdmVPKNLnO47FWiDQwjdotaei5lkIxEPwnGMm7CU3LxedB4J9Z97rkRjMf2thuJruojiAEJcpkz+7Lx84K3aFAeJUi0yhEaA4iHwIwa+nacYa+70NUEYlTLWMlVD9YZnGQ6suosXPP5afZF6gywIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSRiuVAgdiezTVfqFccMS2RPxVbqTAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEBADAr1ocbll0NT9smvrjb1z689+S4Cvnj03DwMTEMcDeM+rRVryfkm6YhZGMyLBxnmTfTLwIfMpuAcT7c9g73Ot1wlj7Q6jXVoppYx1XOkvExntUyQhU/fSZ0+A6GgBm09K7ekBIX7N5qxy24TP1rMZb1D9oo/S86UxWaeL8jKknd4HcnGvW/6LvSGSwsLYjIpD99bQpT8YroH012QURx3TrGv/v+2ag1VaytqDF+mO8cudJ1TooAac0BTwgpd6HgVTg50rOR62Cj/pmkeXL2oq/gzqPZeqsP/OU3jxB+MaP5Hv834TNdrIHny74Okw5cW0lOivbpwFjmkKCWLB09Kio=-----END CERTIFICATE-----
node21_auth0_domain: node21.eu.auth0.com
node21_m2m_client_id: Yz4bvs2n4VznoRR2BEHeGhR2PBe7UpzA
node21_client_id: 5DpiCsm54zazAyJ4hjA2Sphrr8hu2edV
node21_audience: https://osamaoracle.com
node21_m2m_audience: https://osamaoracle.com
node21_m2m_client_secret: KxgFNE5TujY2O4UdQVnqEMAAx_zR1-Hcg2dX1tW0XEbYzFhkGh_4q6yXIevo0KUV
