---

- name: Reboot
  shell: sleep 5 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  listen: Policy updated handler

- name: Wait for the server to come back up
  wait_for_connection:
    delay: 10
    timeout: 900
  listen: Policy updated handler