---

- name: create role docker directory
  file:
    path: /docker/minio
    state: directory
    mode: 0755

- set_fact:
    restart_docker: no

- name: create docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /docker/minio/docker-compose.yml
    mode: 0660
    owner: root
    group: wheel

- name: run service
  docker_compose:
    project_src: /docker/minio/
    pull: yes
    restarted: "{{ restart_docker }}"
  register: run_service_result
