---

- name: create role docker directory
  file:
    path: /docker/hume_review_orchestra
    state: directory
    mode: 0755

- set_fact:
    restart_docker: no

- name: create docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /docker/hume_review_orchestra/docker-compose.yml
    mode: 0660
    owner: root
    group: wheel

- name: Log into  registry
  docker_login:
    registry: "{{ docker_registry_url }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
  changed_when: False

- name: run service
  docker_compose:
    project_src: /docker/hume_review_orchestra/
    pull: yes
    restarted: "{{ restart_docker }}"
  register: run_service_result

- debug:
    var: run_service_result

- name: set local ip address to services
  set_fact:
    service_container_ip:
      frontend: "{{ run_service_result.services['web']['hume_review_orchestra_web_1'].networks.reverse_proxy.IPAddress }}"
      backend: "{{ run_service_result.services['api']['hume_review_orchestra_api_1'].networks.reverse_proxy.IPAddress }}"
      orchestra: "{{ run_service_result.services['orchestra']['hume_review_orchestra_orchestra_1'].networks.reverse_proxy.IPAddress }}"

- name: register frontend to reverse proxy
  include_role:
    name: reverse_proxy_record
  vars:
    server_name: "orchestra.review.hume..com"
    endpoints:
      "/": "http://{{ service_container_ip.frontend }}"


- name: register api to reverse proxy
  include_role:
    name: reverse_proxy_record
  vars:
    server_name: "api.orchestra.review.hume..com"
    endpoints:
      "/": "http://{{ service_container_ip.backend }}:8080"

- name: register orchestra to reverse proxy
  include_role:
    name: reverse_proxy_record
  vars:
    server_name: "o.orchestra.review.hume..com"
    endpoints:
      "/": "http://{{ service_container_ip.orchestra }}:8100"