---
# Create a group for every user and make that their primary group
users_create_per_user_group: true

# If we're not creating a per-user group, then this is the group all users
# belong to
users_group: users

# The default shell for a user if none is specified
users_default_shell: /bin/bash

# Create home dirs for new users? Set this to false if you manage home
# directories in some other way.
users_create_homedirs: true

# Definitions of users managed by this role. To assure the user is present on a particular instance, add its key to the "users_enabled" list.
users:
  Osama:
    name: Osama Mustafa
    sudo: yes
    ssh_key: |
       Your-key
  Test:
    name: Test User
    sudo: yes
    ssh_key: |
      Your-key
  Ubuntu:
    name: Ubuntu user
    sudo: yes
    ssh_key: |
      Your-key
  Osama2:
    name: Osama Osama
    sudo: yes
    ssh_key: |
      Your-key
 