---

- name: Install libselinux-python
  yum:
    name: libselinux-python
    state: present

# Put SELinux in permissive mode, logging actions that would be blocked.
- selinux:
    policy: targeted
    state: permissive
  notify: Policy updated handler

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers